version: '3.8'

services:
  mongo:
    image: mongo:4.4
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: security-portal
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - web-network
      
  backend:
    build: ./backend
    container_name: pfe-backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mongo
    command: npm start
    networks:
      - web-network

  frontend:
    build: ./security-portal
    container_name: pfe-frontend
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend

    environment:
      - NGINX_HOST=security-portal
      - NGINX_PORT=443
    restart: unless-stopped
    networks:
      - web-network

networks:
  web-network:
    driver: bridge  
